apiVersion: v1
kind: Service
metadata:
  name: pgstorm-metrics
  labels:
    app: pgstorm
spec:
  selector:
    app: pgstorm
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
  type: ClusterIP
