global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: pg-loadgen
    static_configs:
      - targets:
          - 'postges-go-load-generator-loadgen-1:9090'
          - 'postges-go-load-generator-loadgen-2:9090'

  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']
